version: '3'
services: 
    app:
        build: .
        volumes: 
            - .:/home/gis
        ports: 
            - "3333:3333" # 改行がいるの？ 8080が、いんでんｔ
        stdin_open: true # docker run -i らしい
        tty: true        # docker run -t らしい
        working_dir: /home/gis
        